# Change these first
owner: odqo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: odqo
    url: https://www.odqo.ch
  - name: lafabriquecirculaire.ch
    url: https://www.lafabriquecirculaire.ch
  - name: fromagerieamstutz.ch
    url: https://www.fromagerieamstutz.ch
  - name: acade-agro.ch
    url: https://www.acade-agro.ch
  - name: art-werk.ch
    url: https://www.art-werk.ch
  - name: urbamonde.org
    url: https://www.urbamonde.org
  - name: habitat-solidaire.ch
    url: https://www.habitat-solidaire.ch/
  - name: co-habitat.net
    url: https://www.co-habitat.net
  - name: CoHabitat.io
    url: https://www.cohabitat.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitoring 24/7"
  # introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
